module cz.upol.logicgo {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;

    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires eu.hansolo.tilesfx;
    requires com.almasb.fxgl.all;
    requires javafx.graphics;
    requires com.fasterxml.jackson.databind;
    requires jakarta.persistence;
    requires org.hibernate.orm.core;
    requires java.desktop;
    requires jdk.management.jfr;
    requires com.fasterxml.jackson.dataformat.yaml;
    requires com.fasterxml.jackson.dataformat.xml;
    requires com.fasterxml.jackson.datatype.jsr310;
    requires annotations;
    requires jbcrypt;
    requires javafx.swing;
    requires com.github.librepdf.openpdf;
    requires fr.brouillard.oss.cssfx;
    requires org.apache.pdfbox;
    requires atlantafx.base;
    requires org.girod.javafx.svgimage;

    opens cz.upol.logicgo to javafx.fxml;
    exports cz.upol.logicgo;
    exports cz.upol.logicgo.controllers.screenControllers to javafx.fxml;
    opens cz.upol.logicgo.controllers.screenControllers to javafx.fxml;
    exports cz.upol.logicgo.util to javafx.fxml;
    opens cz.upol.logicgo.util to javafx.fxml;
    exports cz.upol.logicgo.model.games.entity.user to org.hibernate.orm.core;
    exports cz.upol.logicgo.model.games to org.hibernate.orm.core;
    exports cz.upol.logicgo.model.games.entity.sudoku to org.hibernate.orm.core;
    exports cz.upol.logicgo.model.games.entity.mazes to org.hibernate.orm.core;
    exports cz.upol.logicgo.model.games.entity.bridges to org.hibernate.orm.core;
    exports cz.upol.logicgo.util.converters to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.entity.user to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.entity.sudoku to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.entity.mazes to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.entity.bridges to org.hibernate.orm.core;
    opens cz.upol.logicgo.util.converters to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.entity.setting to org.hibernate.orm.core;
    exports cz.upol.logicgo.model.games.service to javafx.fxml;
    opens cz.upol.logicgo.model.games.service to javafx.fxml;
    exports cz.upol.logicgo.model.games.cqUpdate to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.cqUpdate to org.hibernate.orm.core;
    opens cz.upol.logicgo.misc.export.DTOs to com.fasterxml.jackson.databind;
    opens cz.upol.logicgo.misc.export.DTOs.games to com.fasterxml.jackson.databind;
    opens cz.upol.logicgo.controllers.miscControllers to javafx.fxml;
    exports cz.upol.logicgo.controllers.miscControllers to javafx.fxml;
    exports cz.upol.logicgo.model.games.drawable.elements.sudoku to org.hibernate.orm.core;
    opens cz.upol.logicgo.model.games.drawable.elements.sudoku  to org.hibernate.orm.core;
    opens cz.upol.logicgo.misc.export.DTOs.games.setting to com.fasterxml.jackson.databind;
    exports cz.upol.logicgo.commands to javafx.graphics;
    exports cz.upol.logicgo.controllers.listControllers to javafx.fxml;
    opens cz.upol.logicgo.controllers.listControllers to javafx.fxml;
    exports cz.upol.logicgo.controllers.gameChoiceControllers to javafx.fxml;
    opens cz.upol.logicgo.controllers.gameChoiceControllers to javafx.fxml;
    exports cz.upol.logicgo.controllers.popoverControllers to javafx.fxml;
    opens cz.upol.logicgo.controllers.popoverControllers to javafx.fxml;
    opens cz.upol.logicgo.model.games.entity.export to org.hibernate.orm.core;
    exports cz.upol.logicgo.model.games.entity.export to org.hibernate.orm.core;
    exports cz.upol.logicgo.controllers.exportControllers to javafx.fxml;
    opens cz.upol.logicgo.controllers.exportControllers to javafx.fxml;
    exports cz.upol.logicgo.algorithms.sudoku.layout to com.fasterxml.jackson.databind;
    opens cz.upol.logicgo.algorithms.sudoku.layout to com.fasterxml.jackson.databind;
}